version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - npm install
      - npm install --silent --no-progress -g serverless@3.16.0
  build:
    commands:
      - npm run build
      - serverless deploy
  post_build:
    commands:
      - echo "run tests here"
